# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_form(object):
    def setupUi(self, Login_form):
        Login_form.setObjectName("Login_form")
        Login_form.resize(633, 270)
        Login_form.setStyleSheet("background-color: rgb(119, 171, 255);")
        self.frame = QtWidgets.QFrame(Login_form)
        self.frame.setGeometry(QtCore.QRect(130, 90, 351, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 70, 281, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.username_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.username_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username_edit.setObjectName("username_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_edit)
        self.password_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.password_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_edit.setObjectName("password_edit")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_edit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(120, 140, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(125, 205, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 140, 121, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(125, 205, 127);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(160, 0, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Login_form)
        self.label_4.setGeometry(QtCore.QRect(60, 10, 521, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Login_form)
        QtCore.QMetaObject.connectSlotsByName(Login_form)

    def retranslateUi(self, Login_form):
        _translate = QtCore.QCoreApplication.translate
        Login_form.setWindowTitle(_translate("Login_form", "Login"))
        self.label.setText(_translate("Login_form", "Username:"))
        self.label_2.setText(_translate("Login_form", "Password:"))
        self.pushButton.setText(_translate("Login_form", "Login"))
        self.pushButton_2.setText(_translate("Login_form", "Forgot Password"))
        self.label_3.setText(_translate("Login_form", "Login"))
        self.label_4.setText(_translate("Login_form", "Student management System"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_form = QtWidgets.QWidget()
    ui = Ui_Login_form()
    ui.setupUi(Login_form)
    Login_form.show()
    sys.exit(app.exec_())
